apiVersion: apps/v1
kind: Deployment
metadata:
  name: chromium-rpi${NUM}
  namespace: monitors-ii-nz
  labels:
    environment: production
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: chromium-rpi${NUM}
  template:
    metadata:
      labels:
        app: chromium-rpi${NUM}
        environment: production
    spec:
      automountServiceAccountToken: false
      hostNetwork: true
      hostPID: true
      containers:
      - name: chromium
        image: registry.gitlab.com/ii/nz/chromium:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          privileged: true
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: dev
            mountPath: /dev
          - name: sys
            mountPath: /sys
          - name: unix-socket
            mountPath: /tmp/.X11-unix
          - name: home-user
            mountPath: /home/user
        command:
          - nsenter
          - -t
          - "1"
          - -m
          - -u
          - -n
          - -i
          - su
          - pi
          - -c
          - "whoami ; cat /etc/passwd ; rm -rf /home/pi/.config/chromium; rm -rf /home/pi/.cache/chromium/; chromium --start-fullscreen https://careers-expo.ii.nz/monitor.html"
        env:
          - name: TZ
            value: "Pacific/Auckland"
          - name: DISPLAY
            value: "unix:0"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - pi${NUM}.ii.nz
      volumes:
        - name: dev
          hostPath:
            path: /dev
        - name: sys
          hostPath:
            path: /sys
        - name: unix-socket
          hostPath:
            path: /tmp/.X11-unix
        - name: home-user
          emptyDir: {}
