#ci-sa:noapply=true
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: careers-expo-ii-nz-letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: letsencrypt@ii.coop
    privateKeySecretRef:
      name: careers-expo-ii-nz-letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
