apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: careers-expo-ii-nz
  namespace: careers-expo-ii-nz
spec:
  minReplicas: 1
  maxReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: careers-expo-ii-nz
  targetCPUUtilizationPercentage: 80
