apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: careers-expo-ii-nz
  namespace: careers-expo-ii-nz
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: careers-expo-ii-nz
