#ci-sa:noapply=true
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: careers-expo-ii-nz-ci
  namespace: careers-expo-ii-nz
rules:
  - apiGroups:
      - "apps"
    resources:
      - "deployments"
    verbs:
      - get
      - create
      - update
      - patch
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - "ingresses"
    verbs:
      - get
      - create
      - update
      - patch
  - apiGroups:
      - "policy"
    resources:
      - "poddisruptionbudgets"
    verbs:
      - get
      - create
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - "services"
    verbs:
      - get
      - create
      - update
      - patch
  - apiGroups:
      - "cert-manager.io"
    resources:
      - "certificates"
    verbs:
      - get
      - create
      - update
      - patch
  - apiGroups:
      - "autoscaling"
    resources:
      - "horizontalpodautoscalers"
    verbs:
      - get
      - create
      - update
      - patch
