#ci-sa:noapply=true
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: careers-expo-ii-nz-ci
  namespace: careers-expo-ii-nz
subjects:
  - kind: ServiceAccount
    name: careers-expo-ii-nz-ci
    namespace: careers-expo-ii-nz
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: careers-expo-ii-nz-ci
