apiVersion: v1
kind: Service
metadata:
  name: careers-expo-ii-nz
  namespace: careers-expo-ii-nz
  labels:
    environment: production
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: careers-expo-ii-nz
