#+TITLE: Project Plan

* Goal
We would like to have interactive presentations at the Expo(happening in 3
weeks) that give a nice wow moment to visitors of the booth, showing them an
awesome feature of the cloud and the technology we work with. This document sets
the scope and iteration steps for these presentations.

* Project Description
At our booth, multiple screens will be displaying org-reveal presentations on
some aspect of open source/CNCF. A visitor to the booth can scan one of these
screens and be able to control it, specifically, for a set period of time.
Multiple visitors can be interacting with our presentations at the same time,
each vistior in control of their own screen and their own presentation. This may
be the same presentation some one else is looking at, or a different one.

This means we will need to have a QR code that is dynamically set with the admin
key for that particular presentation.

It would be cool for the visitor controls to include the presentation they are
wanting to look at, and not just the one they scanned, and perhaps some sort of
input they can add that is also displayed on a screen(e.g. a whiteboard that has
their doodle and tag).

* How it works
** Terms
- Server  :: our express server that bootstraps socket.io to handle events passed among clients.
- Client :: a browser that visits the web server.  It can then be turned into a Monitor or a Controller, depending.
- Monitor :: a client responsible for showing a presentation. Most likely will be our large-ass monitors.
- Controller :: a client responsible for controlling the slides of the presentation.  In reveal.js terms, the Monitor is the 'client' and the Controller is the 'master'.
- Event :: a change in state or Message sent from the Server to a Client.
- SotW :: is a list of MonitorStates, or an empty list
- MonitorState :: is an object representing a monitor, who its conected to, and what it's showing, as:
  #+begin_src yaml
  monitorId: ''
  monitorName: ''
  presentation: '' or nil
  socketID: '' or nil
  controllerID: '' or nil
  secret: '' or nil
  dateOfBirth: timestamp
  lastUpdated: timestamp
  #+end_src
- Message :: the content of an Event.
- Event Handler :: the action taken on a Message from an Event given the type of Client.
* Implementation
TODOs:
- [X] fix count for state of the world
- [X] implement prezzie choosing and navigation for all clients involved
- [ ] admin page
* TODO Admin Page
- [ ] accessible at /admin
- [ ] have some basic authentication
- [ ] can see all the monitors and their presentation
- [ ] can set monitor to specific presentation
- [ ] can randomize presentations across all monitors.
- [ ] can trigger monitor to get new name.
- [ ] can set page for all monitors
** Authentication
#+begin_src js
// express server

function authenicationMiddleware (req, res, next) {
    // authentication logic
    const { username, password} = req.body;
    if (users.includes(username) && password === ourPassword) {
        res.sendStatus(200)
        next()
    } else {
        res.sendStatus(403);
        res.json({body: "you don't belong here"});
    }
}

app.get("/admin", authenticationMiddleware, (req, res) => {
    if (res.status === 200)  {
        res.send(ourAdminPage)
    }})
app.get("/", staticPages)

socket.on("refresh all", (payload) => {
    if (payload.auth === ourPassword) {
        //refresh the things
        socket.emit('refreshed!')
    }
})

socket.on("grab all monitors", (payload) => {
    if (payload.auth === ourPassword) {
        socket.emit('refreshed!')
    }
})
#+end_src
* scratch
#+begin_src yaml
# admin is sho  wing presentation on all monitors.
- monitor: 132343234
  name: charlie
  presentation: prezzy1
  socketid: 1332
  secret: 13323
- monitor: 234343234j
  name: charlie
  socketid: 1332
  secret: 13323
  presentation: prezzy1
- monitor: 338383828j
  name: charlie
  socketid: 1332
  secret: 13323
  presentation: prezzy1
- monitor: djsa;3833828
  name: charlie
  presentation: prezzy1
  socketid: 1332
  secret: 13323
#+end_src
#+begin_src yaml
# cycled through the monitors
- monitor: 132343234
  name: dharlie
  presentation: nil
  socketid: nil
  secret: nil
- monitor: 234343234j
  name: ben
  presentation: nil
  socketid: nil
  secret: nil
- monitor: 338383828j
  name: ewtwo
  presentation: nil
  socketid: nil
  secret: nil
#+end_src

#+begin_src yaml
# client syncs with monitor and requests presentation
io.emit("set presentation"{name: dharlie, presentation: prezzy1})
#+end_src

* Logicistics
** Providing monitors new names on prezzie selection
Monitor says to Server, I am ={ monitor }= and would like a new name.
Server finds the current MonitorID in the ={ monitor }= object and rewrites the monitor name.
Server omits a updated Monitor object.
Client Monitor hears omittion, checks the MonitorID for a match and updates it's local monitor object.
